services:
    service.cron:
        class: Abr\ServiceCronBundle\Services\ServiceCron
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
#    abr_service_cron.example:
#        class: Abr\ServiceCronBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
