<?php

namespace Abr\ServiceCronBundle\Repository\Cron;

/**
 * CronSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{
}
