<?php

namespace Abr\ServiceCronBundle\Repository\Cron;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextStep($currentStep, $serieId)
    {
        $qb = $this->createQueryBuilder('step')
            ->join('step.serie', 'serie')
            ->where('serie.status = :statusSerie')
            ->andWhere('step.status <> :statusStep')
            ->andWhere('serie.id = :serieId')
            ->andWhere('step.id > :stepId')
            ->setParameters(array(
                'statusSerie' => 1,
                'statusStep' => 0,
                'serieId' => $serieId,
                'stepId' => $currentStep
            ))
            ->orderBy('step.orderStep', 'ASC')
            ->setMaxResults(1)
            ->getQuery();
        $result = $qb->getResult();

        return (count($result) > 0) ? $result[0] : null;
    }
}
