services:
    teams.table:
        class: Api\LigueBundle\Services\Tables
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
#    ligue.example:
#        class: Api\LigueBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
